apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-restaurant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-restaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-restaurant
  template:
    metadata:
      labels:
        app: postgres-restaurant
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: restaurantdb
            - name: POSTGRES_USER
              value: restaurantuser
            - name: POSTGRES_PASSWORD
              value: restaurantpass
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-restaurant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-restaurant
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
