apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # optional fixed port
